-- 코드를 입력하세요
SELECT DATE_FORMAT(SALES_DATE, '%Y') AS YEAR, 
       DATE_FORMAT(SALES_DATE, '%m') AS MONTH,
       GENDER, 
       COUNT(DISTINCT USER_ID) AS USERS
FROM USER_INFO NATURAL JOIN ONLINE_SALE 
where GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER

