# -- 코드를 입력하세요
# SELECT P.PRODUCT_CODE, P.PRICE * OS.CNT AS SALES
# FROM PRODUCT P JOIN 
#     (SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS CNT
#      FROM OFFLINE_SALE
#      GROUP BY PRODUCT_ID
#     ) OS ON P.PRODUCT_ID = OS.PRODUCT_ID
# ORDER BY 2 DESC, 1;


SELECT P.PRODUCT_CODE, SUM(P.PRICE * OS.SALES_AMOUNT) AS SALES
FROM PRODUCT P JOIN OFFLINE_SALE OS ON P.PRODUCT_ID = OS.PRODUCT_ID
GROUP BY P.PRODUCT_ID
ORDER BY 2 DESC, 1;