-- 코드를 입력하세요
SELECT O.USER_ID, O.PRODUCT_ID
FROM (SELECT USER_ID, PRODUCT_ID, COUNT(PRODUCT_ID) AS CNT FROM ONLINE_SALE GROUP BY USER_ID, PRODUCT_ID) O
WHERE O.CNT > 1
ORDER BY O.USER_ID, O.PRODUCT_ID DESC